Lecture04課題提出
s-nakaji03/Raisetech-AWS pull request #3
Opened 2024-03-24 13:59 UTC by s-nakaji03

いつもお世話になっております。
課題４の提出をいたします。

ご多忙のところ大変恐縮ですが、ご確認のほどよろしくお願いいたします。

2024-03-24 14:31 UTC, MasatoshiMizumoto requested changes
課題自体はできていますが、コメント1点入れております！
ご対応お願いします！！

2024-03-24 14:31 UTC, MasatoshiMizumoto commented on images/lecture04/RDSセキュリティグループ.png
IPアドレスで制限も可能なのですが、セキュリティグループをアタッチできるリソース同士の通信にはIPアドレスを用いない手段もありますので、そちらで実装いただきたいです！

2024-03-24 15:44 UTC, s-nakaji03 commented on images/lecture04/RDSセキュリティグループ.png
ご指摘のほうありがとうございます…
修正したエビデンスを添付いたしましたので、ご確認のほどよろしくお願いいたします。

IPアドレス制限よりもセキュリティグループで制限するメリットとしては安全性がより高まるという認識でよろしいでしょうか？？

2024-03-29 11:35 UTC, MasatoshiMizumoto commented on images/lecture04/RDSセキュリティグループ.png
安全性という以外に、AWSは「IPアドレスは固定するものではない」という思想があるので、いつ変わるやもしれないIPアドレスをソースにしない、という考え方のほうが適切鴨です！

2024-03-29 11:37 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-03-29 11:37 UTC, MasatoshiMizumoto commented on lecture04.md
> +  ![RDSセキュリティグループ](images/lecture04/RDSセキュリティグループ修正.png)
インバウンド設定の画像が2つある理由がこのままだと後でみたときに分からないので、
分かるように何か書いておいてください！

2024-03-30 13:30 UTC, s-nakaji03 commented on images/lecture04/RDSセキュリティグループ.png
そのような思想があるのですね！ご回答いただきましてありがとうございます！

2024-03-30 13:31 UTC, s-nakaji03 commented on lecture04.md
> +  ![RDSセキュリティグループ](images/lecture04/RDSセキュリティグループ修正.png)
ご指摘ありがとうございます…
修正いたしましたのでご確認のほどよろしくお願いいたします！

2024-03-30 22:38 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-03-30 23:56 UTC, merged