第10回課題提出
s-nakaji03/Raisetech-AWS pull request #7
Opened 2024-04-23 15:30 UTC by s-nakaji03

いつもお世話になっております。
第10回課題を提出いたします。
お忙しいところ恐縮ですが、ご確認のほどよろしくお願いいたします。

2024-04-24 12:14 UTC, MasatoshiMizumoto requested changes
以下見直しお願いします！！

- 各種CFnファイル
  - EOFの警告マークが出ている
- Outputs名称
  - IDが含まれるなら名称にもID、CIDRが含まれるならCIDR、と名前から明確に中身の種別がわかるように

2024-04-24 13:58 UTC, s-nakaji03 commented
> 以下見直しお願いします！！
> 
> * 各種CFnファイル
>   * EOFの警告マークが出ている
> * Outputs名称
>   * IDが含まれるなら名称にもID、CIDRが含まれるならCIDR、と名前から明確に中身の種別がわかるように

ご確認いただきありがとうございます！
"daf418f"にてEOF警告マーク及びOutputs名称を変更いたしましたので、ご確認のほどよろしくお願いいたします。

2024-04-24 15:00 UTC, MasatoshiMizumoto commented
> > 以下見直しお願いします！！
> > 
> > * 各種CFnファイル
> >   
> >   * EOFの警告マークが出ている
> > * Outputs名称
> >   
> >   * IDが含まれるなら名称にもID、CIDRが含まれるならCIDR、と名前から明確に中身の種別がわかるように
> 
> ご確認いただきありがとうございます！ "daf418f"にてEOF警告マーク及びOutputs名称を変更いたしましたので、ご確認のほどよろしくお願いいたします。

Output名はVPCを例に挙げましたが、対象はVPCだけではないので他も確認ください🙏

2024-04-25 13:12 UTC, s-nakaji03 commented
> Output名はVPCを例に挙げましたが、対象はVPCだけではないので他も確認ください🙏

早とちりしまして大変申し訳ございません。
改めてマネジメントコンソールで各リソースを確認したところリソース名と英数字等の一意の組み合わせが続く形式でしたので、セキュリティグループとルートテーブルのアウトプットにもIDと認識できるように付け加えを行いました！

2024-04-25 13:19 UTC, s-nakaji03 commented
> Output名はVPCを例に挙げましたが、対象はVPCだけではないので他も確認ください🙏

早とちりしまして大変申し訳ございません。
改めてマネジメントコンソールで各リソースを確認したところリソース名と英数字等の一意の組み合わせが続く形式でしたので、セキュリティグループとルートテーブルのアウトプットにもIDと認識できるように付け加えを行いました！

2024-04-25 13:44 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-04-25 14:17 UTC, merged